### ISSUE TITLE
missing content and trust issues

### ISSUE THREAD

**Issue by rw86347** [SurveyMonkey/surveymonkey-ios-sdk#1]
This might be two unrelated issues.

I have moved your exact example code into my app, and am loading it in a modal view.  Which could be the cause of the screen being black.  However I am also getting some errors on the debug screen....

done loading survey
Not trusting connection to host www.surveymonkey.com

**Comment by benleiken** [comment]
@rw86347 The SDK is presented in its own modal view (via presentFromViewController), so that might cause issues if you're attempting to present it from a modal view. Can you give me a bit more info about how you're attempting to present the SDK?

As for the errors -- that's why we're in beta :) I've fixed that bug and will be pushing  a new build to members of the private beta soon. If you've signed up, expect to hear from us soon.
