### ISSUE TITLE
Long delay calling `presentFromViewController`

### ISSUE THREAD

**Issue by Aranda** [SurveyMonkey/surveymonkey-ios-sdk#21]
I'm seeing delays of 5+ seconds presenting the survey view controller (before the view is displayed: then there is an extra delay with the spinner whilst the survey loads). Is this expected?

I've tried various workarounds and even the sample survey hash has this issue.

**Comment by benleiken** [comment]
Hey @Aranda, unfortunately yes, this is expected behavior. We prefetch the some survey data before presenting the View Controller (to ensure that the survey hasn't been closed for collection, etc) and then there is a slight delay associated with allocating and loading up the UIWebView we use to display the survey.

Latency also varies according to geographical location -- if you're attempting to load the survey outside of the US, that typically adds a few extra seconds to overall load time.

We're working on reducing latency/load times internationally, so stay tuned. We'll likely move to WKWebviews in the next release of the SDK as well, which should speed up rendering times.

**Comment by Aranda** [comment]
Hi @benleiken, thanks for the explanation. I've worked around it by showing a progress spinner until the survey View Controller is displayed. I came across the same issue in the android SDK.

The total load time is not really an issue, it is the fact that the SDK is doing a pre-fetch before showing the survey web view, meaning the user is waiting for 5 seconds for any response to their button press. Ideally this delay would be handled within the SDK(s), as it makes a simple integration much less simple. Would you expect the move to WKWebviews to resolve this initial prefetch lag?

I have another UX problem that I can't work around, but I'll open another issue for that. Thanks!
