### ISSUE TITLE
Survey updates

### ISSUE THREAD

**Issue by kerencic** [SurveyMonkey/surveymonkey-ios-sdk#4]
My survey questions will change every week. So the AcceptInterval is set to 1 week. What happens with the UIAlertView if user ended my first survey and i changed this survey before one week (AcceptInterval) is passed? Will UIAlertView appear to notify my user that a new survey is out? Also one bug that you could check. I closed my mobile collector, but the alert is still appearing after the AcceptInterval or DeclineInterval is up.

**Comment by benleiken** [comment]
@kerencic Regarding your first question: the schedule that determines when the UIAlertView is shown is not tied to the content of the survey. So, no, the intercept will continue to adhere to the whatever schedule you set for it in `scheduleInterceptFromViewController `. If you wanted to consistently display a new survey every week, you could program your own scheduling flow and just use `[_feedbackController presentFromViewController:self animated:YES completion:nil]` to display the survey at the proper time.

And, second, good catch! I'll have that bug fixed in the next day or so. Thank you for the great feedback!
