### ISSUE TITLE
scheduleInterceptFromViewController not working correctly

### ISSUE THREAD

**Issue by mikemonaco** [SurveyMonkey/surveymonkey-ios-sdk#45]
1) scheduleInterceptFromViewController seems to never work the first time it's called on a device, even if all of the intervals are set to zero (0). The second time it is called it presents the UIAlertView.

2) scheduleInterceptFromViewController doesn't seem to work on iOS 8.4 (simulator).

3) If you call scheduleInterceptFromViewController with all 3 intervals set to 1 day (86,400 seconds), and you take the survey, but then you change the intervals back to 0 and re-run the application, the survey will not show. This seems like a bug. It should be checking against the current call-time interval values, rather than the interval values that were set at the time the survey was previously taken.

**Comment by benleiken** [comment]
@mikemonaco I made some modifications to the intercept in the latest release (2.0.2) -- both #1 and #3 should definitely be addressed. Let me know if not.

We're likely going to drop iOS 8 support soon, since 12 will be out soon and 8 usage is tiny at this point. Let me know if #2 is still an issue, but I don't know that we'll address it.

**Comment by mikemonaco** [comment]
confirmed 1 and 3 are fixed as you mentioned. 2 still remains, but I understand you point about dropping iOS 8 support soon. does scheduleInterceptFromViewController use some iOS9+ features?  thanks for the fixes!
